theme: jekyll-theme-slate

# Smart-Breathalyzer

  ## Synopsis
  Smart Breathalyzer 1.0 is a project which is mainly targeted for the Police Department in Sri Lanka. Until now they use conventional balloon test to identify drunk drivers. Providing an easy, efficient and more secure IOT based solution to replace old conventional method our aim is to reduce vehicle accidents caused by drunken drivers and uplift the productivity and reliabilty of the Police Department. 
  
  Breathalyzer 1.0 comprised with an embedded part and network part. Hence it can communicate with a remote server sending Alcohol level, Vehicle number and Driver license ID. This device has its own unique id registered in the server. Once the police officer checks a driver breath alcohol level is displayed on the device display and if it is over the specified limit device will automatically prompt to enter Vehicle Number and Driver License ID. Then all the data is sent to remote server. Smart Breathalyzer device consists of an Arduino Mega board, a keypad, MQ3 alcohol sensor, LCD display, GSM/GPRS module. 
  
   A web app is also integrated in the process to access, organize and analyze data in the remote database. Web App is accessible only for authorized officers.
   
Backend server and front end web application for reporting statistics of issued data from smart-breathalysers
